version: "3.6"
services:
  backend:
    build: .
    container_name: backend_server
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ~/backend_photo:/photo    
networks:
    default:
        external:
            name: cosmetic_network

